<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'title' => 'Fjallraven - Foldsack No. 1 Backpack, Acomoda até 15 laptops',
                'price' => '109.95',
                'description' => 'Seu pacote perfeito para uso diário e caminhadas pela floresta. Armazene seu laptop (até 15 polegadas) na manga protegida, suas necessidades cotidianas.',
                'category' => 'homens',
                'image' => 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
                'rating' => ['rate' => 7.9, 'count' => 120],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 2,
                'title' => 'Camisetas Masculinas Casuais Premium Ajustadas Slim',
                'price' => '22.30',
                'description' => 'Estilo ajustado, gola longa em contraste com costura de raglan, abotoaduras de três botões na parte frontal de henley, tecido leve e macio para uso respirável e confortável. E camisas costuradas sólidas com gola redonda feitas para durabilidade e um ótimo ajuste para vestir casualmente e fãs apaixonados de beisebol. O estilo Henley inclui uma gola redonda com uma abotoadura de três botões.',
                'category' => 'homens',
                'image' => 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
                'rating' => ['rate' => 8.1, 'count' => 259],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 3,
                'title' => 'Jaqueta de Algodão Masculina',
                'price' => '55.99',
                'description' => 'Ótimas jaquetas de capa externa para Primavera/Outono/Inverno, adequadas para muitas ocasiões, como trabalho, trilha, acampamento, escalada de montanha/rochas, ciclismo, viagens ou outras atividades ao ar livre. Boa escolha de presente para você ou um membro da sua família. Um carinho quente para Pai, marido ou filho neste Dia das Crianças ou Natal.',
                'category' => 'homens',
                'image' => 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
                'rating' => ['rate' => 6.7, 'count' => 500],
                'badge' => 'Estoque Acabando!',
                'shipping' => '',
            ],
            [
                'id' => 4,
                'title' => 'Casual Masculino Slim Fit',
                'price' => '15.99',
                'description' => 'A cor pode ser ligeiramente diferente entre o que é mostrado na tela e na prática. / Por favor, note que os tipos corporais variam de pessoa para pessoa, portanto, informações detalhadas sobre o tamanho devem ser revisadas abaixo na descrição do produto.',
                'category' => 'homens',
                'image' => 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
                'rating' => ['rate' => 9.1, 'count' => 430],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 5,
                'title' => "Brincanteira de Cobra Dragão Naga Ouro e Prata da Coleção Legendas da John Hardy",
                'price' => '695.00',
                'description' => "Da nossa Coleção Legendas, a Naga foi inspirada na dragã mitológica que protege a pérola do oceano. Use voltada para dentro para ser abençoada com amor e abundância, ou voltada para fora para proteção.",
                'category' => 'joalheria',
                'image' => 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
                'rating' => ['rate' => 8.6, 'count' => 400],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 6,
                'title' => 'Petite Micropave de Ouro Puro',
                'price' => '168.00',
                'description' => 'Garantia de Satisfação. Devolver ou trocar qualquer pedido dentro de 30 dias. Projeto e venda pelo Hafeez Center nos Estados Unidos. Garantia de Satisfação. Devolver ou trocar qualquer pedido dentro de 30 dias.',
                'category' => 'joalheria',
                'image' => 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
                'rating' => ['rate' => 7.9, 'count' => 70],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 7,
                'title' => 'Princesa Revestida em Ouro Branco',
                'price' => '9.99',
                'description' => "Anel de Promessa de Diamante Solitário Clássico Criado para Ela. Presentes para enriquecer ainda mais seu amor para Casamento, Aniversário, Dia dos Namorados...",
                'category' => 'joalheria',
                'image' => 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
                'rating' => ['rate' => 9, 'count' => 400],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 8,
                'title' => 'Orelhas de Pomba-rei Perfuradas Revestidas em Ouro Rosa',
                'price' => '10.99',
                'description' => 'Orelhas Duplas de Túnel Aumentadas Revestidas em Ouro Rosa. Feitas de Aço Inoxidável 316L',
                'category' => 'joalheria',
                'image' => 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
                'rating' => ['rate' => 6.9, 'count' => 100],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 9,
                'title' => 'Disco Rígido Externo Portátil WD 2TB Elements - USB 3.0',
                'price' => '64.00',
                'description' => 'Compatibilidade com USB 3.0 e USB 2.0 Transferência rápida de dados Melhora o desempenho do PC Alta capacidade; Formato compatível NTFS para Windows 10, Windows 8.1, Windows 7; Reformatação pode ser necessária para outros sistemas operacionais; A compatibilidade pode variar dependendo da configuração de hardware e sistema operacional do usuário',
                'category' => 'eletronicos',
                'image' => 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
                'rating' => ['rate' => 9.3, 'count' => 203],
                'badge' => 'Preço Abaixou',
                'shipping' => '',
            ],
            [
                'id' => 10,
                'title' => 'SSD Interno SanDisk SSD PLUS 1TB - SATA III 6 Gb/s',
                'price' => '109.00',
                'description' => 'Atualização fácil para inicialização mais rápida, desligamento, carga e resposta de aplicativos (Comparado a disco rígido HDD 5400 RPM SATA 2.5”; Baseado em especificações publicadas e testes internos de benchmark usando pontuações PCMark Vantage) Aumenta o desempenho de escrita em rajadas, tornando-o ideal para cargas de trabalho típicas de PC Equilíbrio perfeito entre desempenho e confiabilidade Velocidades de leitura/gravação de até 535 MB/s/450 MB/s (Baseado em testes internos; O desempenho pode variar dependendo da capacidade do disco, dispositivo host, sistema operacional e aplicação)',
                'category' => 'eletronicos',
                'image' => 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
                'rating' => ['rate' => 8.9, 'count' => 470],
                'badge' => 'Vendendo Rápido!',
                'shipping' => 'Frete Grátis!',
            ],
            [
                'id' => 11,
                'title' => 'SSD Silicon Power 256GB 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
                'price' => '109.00',
                'description' => 'Aplique-se tecnologia 3D NAND flash para entregar altas velocidades de transferência Notáveis velocidades de transferência que permitem inicialização mais rápida e melhor desempenho geral do sistema. A avançada tecnologia SLC Cache permite aumento de desempenho e vida útil mais longa Design fino de 7mm adequado para Ultrabooks e notebooks ultra-eslembrosos. Suporta comando TRIM, tecnologia de Coleta de Resíduos, RAID e ECC (Verificação e Correção de Erros) para fornecer desempenho otimizado e maior confiabilidade.',
                'category' => 'eletronico',
                'image' => 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
                'rating' => ['rate' => 5.8, 'count' => 319],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 12,
                'title' => 'Unidade de Armazenamento Portátil WD 4TB para Jogos Funciona com PlayStation 4',
                'price' => '114.00',
                'description' => "Aproveite sua experiência de jogos na PS4, Jogue em qualquer lugar, Rápido e fácil, configuração, Design elegante com alta capacidade, Garantia limitada de fabricante de 3 anos",
                'category' => 'eletronicos',
                'image' => 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg',
                'rating' => ['rate' => 8.8, 'count' => 400],
                'badge' => 'Pré-venda',
                'shipping' => '',
            ],
            [
                'id' => 13,
                'title' => 'Câmera Digital Sony Alpha a6000 ILCE-6000 Body Only',
                'price' => '598.00',
                'description' => 'Compre a câmera digital Sony Alpha a6000 ILCE-6000 Body Only com confiança. Esta câmera possui um sensor CMOS de 24,2 MP e uma lente de objetivo fixo de 16-50 mm. Com a tecnologia BIONZ X™, ela oferece processamento de imagem rápido e eficiente, capturando imagens nítidas mesmo em condições de baixa luz. A câmera também suporta gravação de vídeo 4K e tem uma tela tiltable de 3,0 polegadas para composição de imagens.',
                'category' => 'fotografia',
                'image' => 'https://fakestoreapi.com/img/41fVwB-IHKL._AC_SL1000_.jpg',
                'rating' => ['rate' => 8.5, 'count' => 320],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 14,
                'title' => 'Headphones Wireless Bluetooth On-Ear 3.5mm Jack',
                'price' => '26.99',
                'description' => 'Os Headphones Wireless Bluetooth On-Ear 3.5mm Jack são perfeitos para quem busca conveniência sem comprometer a qualidade sonora. Com conectividade Bluetooth e entrada de áudio 3.5mm, eles se adaptam a qualquer dispositivo. Os headphones possuem alto-falantes de 40 mm para reprodução clara de música e chamadas claras. Eles também têm um design ergonômico para conforto durante longas sessões de escuta.',
                'category' => 'acessórios',
                'image' => 'https://fakestoreapi.com/img/71kpZkX6PVL._AC_SL1500_.jpg',
                'rating' => ['rate' => 8.2, 'count' => 200],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 15,
                'title' => 'Mouse Gamer Logitech G Pro X Superlight',
                'price' => '69.99',
                'description' => 'O Mouse Gamer Logitech G Pro X Superlight é projetado para jogadores profissionais que buscam precisão e agilidade. Com um peso de apenas 63 gramas, ele oferece movimento suave e controle preciso. Ele possui botões personalizáveis e uma tampa removível para personalização. O mouse também suporta conexão via Bluetooth ou cabo USB, garantindo flexibilidade em diferentes plataformas.',
                'category' => 'acessórios',
                'image' => 'https://fakestoreapi.com/img/91aHR0cHM6Ly90LmFwcHYyOC45c3xzdHNhLW1pbWFnZXMuY29tLzAvMy8yMDIwL3dvcmxkL2loZWxmaWNhbC1wYWdlcy80MC9naXRodWIuanBlMkZwcy5qcGc=.jpg',
                'rating' => ['rate' => 9.1, 'count' => 300],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 16,
                'title' => 'Smartphone Samsung Galaxy Z Fold 2 5G',
                'price' => '1999.00',
                'description' => 'O Smartphone Samsung Galaxy Z Fold 2 5G redefine o que é possível em um smartphone, com uma tela dinâmica que se transforma em um tablet quando dobrada. Com 6,23 polegadas quando dobrado e 7,62 polegadas quando aberto, ele oferece uma experiência visual imersiva. Equipado com Snapdragon 865+, ele garante desempenho superior e velocidade de rede 5G. A bateria de 4400mAh mantém o dispositivo alimentado por todo o dia.',
                'category' => 'telefonia',
                'image' => 'https://fakestoreapi.com/img/81fPUYfsckL._AC_SL1500_.jpg',
                'rating' => ['rate' => 8.8, 'count' => 350],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 17,
                'title' => 'Tablet Apple iPad Mini (2019) 64GB - Space Gray',
                'price' => '399.00',
                'description' => 'O Tablet Apple iPad Mini (2019) 64GB - Space Gray é uma versão compacta e poderosa do iPad, perfeito para leitura, navegação na web, email, mensagens e muito mais. Com um display de 7,9 polegadas, ele oferece uma experiência visual clara e vívida. O chip A12 Bionic proporciona desempenho rápido e eficiente, enquanto o iOS facilita a organização e compartilhamento de conteúdo. A bateria de longa duração garante até 10 horas de uso contínuo.',
                'category' => 'dispositivos digitais',
                'image' => 'https://fakestoreapi.com/img/71-6ys3RPDL._AC_SL1500_.jpg',
                'rating' => ['rate' => 9.3, 'count' => 500],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 18,
                'title' => 'Notebook Dell Inspiron 14 3000',
                'price' => '549.99',
                'description' => 'O Notebook Dell Inspiron 14 3000 é uma opção versátil para estudantes, profissionais e criadores. Com um processador Intel Core i3, ele oferece desempenho suficiente para tarefas diárias e multitarefa. O display de 14 polegadas apresenta detalhes nítidos, enquanto a bateria de longa duração garante até 8 horas de uso contínuo. O notebook vem com 4 GB de RAM e 128 GB de armazenamento interno, expandível via SD.',
                'category' => 'computadores',
                'image' => 'https://fakestoreapi.com/img/71kJZ1v1aPL._AC_SL1500_.jpg',
                'rating' => ['rate' => 7.9, 'count' => 250],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 19,
                'title' => 'Console Nintendo Switch Lite - Turquoise',
                'price' => '199.99',
                'description' => 'A Console Nintendo Switch Lite - Turquoise é a versão portátil da popular Nintendo Switch, perfeita para jogos em movimento. Sem a necessidade de uma TV, ela oferece uma experiência de jogo portátil completa. Com um display de 5,5 polegadas, ela é ideal para jogos locais ou viagens. A console vem com todos os jogos necessários para começar, incluindo uma variedade de títulos populares disponíveis para download.',
                'category' => 'videojogos',
                'image' => 'https://fakestoreapi.com/img/71-2nG0DKBL._AC_SL1500_.jpg',
                'rating' => ['rate' => 9.2, 'count' => 450],
                'badge' => '',
                'shipping' => '',
            ],
            [
                'id' => 20,
                'title' => 'Smartwatch Xiaomi Mi Smart Band 4 NFC',
                'price' => '39.99',
                'description' => 'O Smartwatch Xiaomi Mi Smart Band 4 NFC é um acessório inteligente que monitora sua saúde e fitness. Ele rastreia passos, distância percorrida, calorias queimadas e muito mais. Com suporte para NFC, ele permite pagamentos não contato em lojas compatíveis. O smartband possui uma tela AMOLED de 1,04 polegadas e uma bateria de longa duração que dura até 9 dias. Ele é resistente à água e ideal para uso diário.',
                'category' => 'smartwatches',
                'image' => 'https://fakestoreapi.com/img/6109101165632._AC_SL1500_.jpg',
                'rating' => ['rate' => 8.5, 'count' => 350],
                'badge' => '',
                'shipping' => '',
            ]
        ];

        foreach ($products as $productData) {
            Product::create([
                'id' => $productData['id'],
                'title' => $productData['title'],
                'price' => $productData['price'],
                'description' => $productData['description'],
                'category' => $productData['category'],
                'image' => $productData['image'],
                'rating' => json_encode($productData['rating']),
                'badge' => $productData['badge'] ?? '',
                'shipping' => $productData['shipping'] ?? '',
            ]);
        }
    }
}
